### ISSUE TITLE
No funciona orden en los marcadores

### ISSUE THREAD

**Issue by JHORJE18** [semoal/KingdomOfWords#1]
En la [sección de los Marcadores](https://www.kingdomofwords.com/views/ranking), no funcionan los modos para ordenar los datos de forma ascendiente o descendiente, al igual que ordenarlos según el nombre / nivel / precision...

**Comment by semoal** [comment]
El orden de la sección de marcadores, esta mal enfocada al menos por el momento. 
Funciona correctamente, solo que nombre, nivel o precisión tiene que ser una opción de estas si o si y luego hay que decidir en que orden quieres ordenar ascendente o descendente.
