### ISSUE TITLE
Se reciben dos veces la validación

### ISSUE THREAD

**Issue by JHORJE18** [semoal/KingdomOfWords#3]
Al registrarme he recibido el correo de validación, entró en el enlace, indico mi nombre de usuario y da éxito en la validación. Después de un rato jugando recibo otro correo exactamente igual de validar la cuenta.
![image](https://cloud.githubusercontent.com/assets/22963723/23235713/d6e92942-f956-11e6-9a7b-e1441f3d7cbf.png)

**Comment by semoal** [comment]
Reparado en la nueva versión
